version: '3.8'

services:
  backend:
    build: ./backend
    container_name: truthguard-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:truthguard
      - JWT_SECRET=truthguard-secret-key-for-jwt-token-generation-and-validation-2024
      - JWT_EXPIRATION=86400000
    volumes:
      - ./logs:/app/logs
    networks:
      - truthguard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: truthguard-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - truthguard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  truthguard-network:
    driver: bridge

volumes:
  logs: 